clang++ -o lectura_traza ../../herramientas/lectura_traza.cpp
./lectura_traza ../large/acctransf-base-1.trz > acctransf-base-1.txt
./lectura_traza ../large/acctransf-base-2.trz > acctransf-base-2.txt
./lectura_traza ../large/acctransf-base-3.trz > acctransf-base-3.txt
./lectura_traza ../large/acctransf-base-4.trz > acctransf-base-4.txt
./lectura_traza ../large/acctransf-base-5.trz > acctransf-base-5.txt
./lectura_traza ../large/boundint-base-1.trz > boundint-base-1.txt
./lectura_traza ../large/boundint-base-2.trz > boundint-base-2.txt
./lectura_traza ../large/boundint-base-3.trz > boundint-base-3.txt
./lectura_traza ../large/boundint-base-4.trz > boundint-base-4.txt
./lectura_traza ../large/boundint-base-5.trz > boundint-base-5.txt
./lectura_traza ../large/densinc-base-1.trz > densinc-base-1.txt 
./lectura_traza ../large/densinc-base-2.trz > densinc-base-2.txt
./lectura_traza ../large/densinc-base-3.trz > densinc-base-3.txt
./lectura_traza ../large/densinc-base-4.trz > densinc-base-4.txt
./lectura_traza ../large/densinc-base-5.trz > densinc-base-5.txt
./lectura_traza ../large/denstransf-base-1.trz > denstransf-base-1.txt
./lectura_traza ../large/denstransf-base-2.trz > denstransf-base-2.txt
./lectura_traza ../large/denstransf-base-3.trz > denstransf-base-3.txt 
./lectura_traza ../large/denstransf-base-4.trz > denstransf-base-3.txt
./lectura_traza ../large/denstransf-base-3.trz > denstransf-base-3.txt
./lectura_traza ../large/denstransf-base-4.trz > denstransf-base-4.txt
./lectura_traza ../large/denstransf-base-5.trz > denstransf-base-5.txt
./lectura_traza ../large/initacc-base-1.trz > initacc-base-1.txt   
./lectura_traza ../large/initacc-base-2.trz > initacc-base-2.trz 
./lectura_traza ../large/initacc-base-3.trz > initacc-base-2.trz
./lectura_traza ../large/initacc-base-2.trz > initacc-base-2.trz
./lectura_traza ../large/initacc-base-3.trz > initacc-base-3.trz
./lectura_traza ../large/initacc-base-4.trz > initacc-base-4.trz
./lectura_traza ../large/initacc-base-5.trz > initacc-base-4.trz
./lectura_traza ../large/initacc-base-4.trz > initacc-base-4.trz
./lectura_traza ../large/initacc-base-5.trz > initacc-base-5.trz
./lectura_traza ../large/motion-base-1.trz > motion-base-1.trz  
./lectura_traza ../large/motion-base-2.trz > motion-base-2.trz
./lectura_traza ../large/motion-base-3.trz > motion-base-3.trz
./lectura_traza ../large/motion-base-4.trz > motion-base-4.trz
./lectura_traza ../large/motion-base-5.trz > motion-base-5.trz
./lectura_traza ../large/partcol-base-1.trz > partcol-base-1.txt
./lectura_traza ../large/partcol-base-2.trz > partcol-base-2.txt
./lectura_traza ../large/partcol-base-3.trz > partcol-base-3.txt
./lectura_traza ../large/partcol-base-4.trz > partcol-base-4.txt
./lectura_traza ../large/partcol-base-5.trz > partcol-base-5.txt
./lectura_traza ../large/repos-base-1.trz > repos-base-1.txt
./lectura_traza ../large/repos-base-2.trz > repos-base-2.txt
./lectura_traza ../large/repos-base-3.trz > repos-base-3.txt
./lectura_traza ../large/repos-base-4.trz > repos-base-4.txt
./lectura_traza ../large/repos-base-5.trz > repos-base-5.txt
